name: flutter_extension
description: "Flutter extension"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  shared_preferences:
  flutter_screenutil:
  flutter_svg:
  flutter_spinkit:
  cached_network_image:
  shimmer: 
  fl_chart: ^1.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/language/
    - assets/images/
    - assets/icons/
  fonts:
    - family: TikTokSans
      fonts:
        - asset: assets/fonts/TikTokSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/TikTokSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/TikTokSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TikTokSans-Bold.ttf
          weight: 700
